# Generated by Django 5.0.6 on 2024-06-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_exercise_description_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planexercise',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
