# Generated by Django 5.0.6 on 2024-06-22 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_trainingplan_owner_trainingplanaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.group'),
        ),
    ]
