# Generated by Django 5.0.6 on 2024-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_training_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
