# Generated by Django 5.0.6 on 2024-06-24 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='trainers',
            field=models.ManyToManyField(blank=True, null=True, related_name='trained_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
