# Generated by Django 5.0.6 on 2024-06-24 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_group_members_alter_group_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='trained_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
