# Generated by Django 5.0.6 on 2024-06-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_group_members_alter_group_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('accepted', 'Accepted'), ('denied', 'Denied')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='type',
            field=models.CharField(choices=[('group_member', 'Group Member'), ('group_trainer', 'Group Trainer')], max_length=100),
        ),
    ]
